/*
-- Query: select * from tb_cidade
LIMIT 0, 1000

-- Date: 2021-08-11 20:34
*/
INSERT INTO `` (`id`,`nm_cidade`) VALUES (1,'Acrelândia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (2,'Assis Brasil');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (3,'Brasiléia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (4,'Bujari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (5,'Capixaba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (6,'Cruzeiro do Sul');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (7,'Epitaciolândia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (8,'Feijó');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (9,'Jordão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (10,'Mâncio Lima');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (11,'Manoel Urbano');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (12,'Marechal Thaumaturgo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (13,'Plácido de Castro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (14,'Porto Acre');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (15,'Porto Walter');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (16,'Rio Branco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (17,'Rodrigues Alves');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (18,'Santa Rosa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (19,'Sena Madureira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (20,'Senador Guiomard');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (21,'Tarauacá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (22,'Xapuri');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (23,'Água Branca');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (24,'Alazão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (25,'Alecrim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (26,'Anadia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (27,'Anel');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (28,'Anum Novo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (29,'Anum Velho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (30,'Arapiraca');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (31,'Atalaia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (32,'Baixa da Onça');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (33,'Baixa do Capim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (34,'Bálsamo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (35,'Bananeiras');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (36,'Barra de Santo Antônio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (37,'Barra de São Miguel');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (38,'Barra do Bonifácio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (39,'Barra Grande');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (40,'Batalha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (41,'Batingas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (42,'Belém');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (43,'Belo Monte');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (44,'Boa Sorte');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (45,'Boa Vista');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (46,'Boa Vista');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (47,'Boca da Mata');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (48,'Bom Jardim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (49,'Bonifácio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (50,'Branquinha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (51,'Cacimbinhas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (52,'Cajarana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (53,'Cajueiro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (54,'Caldeirões de Cima');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (55,'Camadanta');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (56,'Campestre');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (57,'Campo Alegre');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (58,'Campo Grande');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (59,'Canaã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (60,'Canafístula');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (61,'Canapi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (62,'Canastra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (63,'Cangandu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (64,'Capela');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (65,'Carneiros');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (66,'Carrasco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (67,'Chã Preta');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (68,'Coité do Nóia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (69,'Colônia Leopoldina');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (70,'Coqueiro Seco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (71,'Coruripe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (72,'Coruripe da Cal');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (73,'Craíbas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (74,'Delmiro Gouveia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (75,'Dois Riachos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (76,'Entremontes');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (77,'Estrela de Alagoas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (78,'Feira Grande');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (79,'Feliz Deserto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (80,'Flexeiras');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (81,'Gaspar');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (82,'Girau do Ponciano');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (83,'Ibateguara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (84,'Igaci');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (85,'Igreja Nova');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (86,'Inhapi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (87,'Jacaré dos Homens');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (88,'Jacuípe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (89,'Japaratinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (90,'Jaramataia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (91,'Jenipapo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (92,'Joaquim Gomes');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (93,'Jundiá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (94,'Junqueiro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (95,'Lagoa da Areia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (96,'Lagoa da Canoa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (97,'Lagoa da Pedra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (98,'Lagoa Dantas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (99,'Lagoa do Caldeirão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (100,'Lagoa do Canto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (101,'Lagoa do Exú');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (102,'Lagoa do Rancho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (103,'Lagoa do Rancho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (104,'Lajes do Caldeirão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (105,'Laranjal');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (106,'Limoeiro de Anadia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (107,'Maceió');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (108,'Major Isidoro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (109,'Mar Vermelho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (110,'Maragogi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (111,'Maravilha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (112,'Marechal Deodoro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (113,'Maribondo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (114,'Massaranduba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (115,'Mata Grande');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (116,'Matriz de Camaragibe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (117,'Messias');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (118,'Minador do Negrão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (119,'Monteirópolis');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (120,'Moreira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (121,'Munguba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (122,'Murici');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (123,'Novo Lino');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (124,'Olho D\'Água Grande');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (125,'Olho D\'Água das Flores');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (126,'Olho D\'Água de Cima');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (127,'Olho D\'Água do Casado');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (128,'Olho D\'Água dos Dandanhas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (129,'Olivença');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (130,'Ouro Branco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (131,'Palestina');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (132,'Palmeira de Fora');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (133,'Palmeira dos índios');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (134,'Pão de Açúcar');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (135,'Pariconha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (136,'Paripueira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (137,'Passo de Camaragibe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (138,'Pau D\'Arco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (139,'Pau Ferro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (140,'Paulo Jacinto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (141,'Penedo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (142,'Piaçabuçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (143,'Pilar');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (144,'Pindoba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (145,'Piranhas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (146,'Poção');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (147,'Poço da Pedra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (148,'Poço das Trincheiras');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (149,'Porto Calvo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (150,'Porto de Pedras');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (151,'Porto Real do Colégio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (152,'Poxim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (153,'Quebrangulo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (154,'Riacho do Sertão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (155,'Riacho Fundo de Cima');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (156,'Rio Largo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (157,'Rocha Cavalcante');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (158,'Roteiro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (159,'Santa Efigênia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (160,'Santa Luzia do Norte');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (161,'Santana do Ipanema');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (162,'Santana do Mundaú');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (163,'Santo Antônio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (164,'São Brás');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (165,'São José da Laje');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (166,'São José da Tapera');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (167,'São Luís do Quitunde');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (168,'São Miguel dos Campos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (169,'São Miguel dos Milagres');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (170,'São Sebastião');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (171,'Sapucaia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (172,'Sapucaia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (173,'Satuba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (174,'Senador Rui Palmeira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (175,'Serra da Mandioca');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (176,'Serra do São José');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (177,'Taboleiro do Pinto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (178,'Taboquinha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (179,'Tanque D\'Arca');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (180,'Taquarana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (181,'Tatuamunha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (182,'Teotônio Vilela');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (183,'Traipu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (184,'União dos Palmares');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (185,'Usina Camaçari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (186,'Viçosa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (187,'Vila Aparecida');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (188,'Vila São Francisco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (189,'Alvarães');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (190,'Amatari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (191,'Amaturá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (192,'Anamã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (193,'Anori');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (194,'Apuí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (195,'Ariaú');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (196,'Atalaia do Norte');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (197,'Augusto Montenegro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (198,'Autazes');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (199,'Axinim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (200,'Badajós');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (201,'Balbina');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (202,'Barcelos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (203,'Barreirinha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (204,'Benjamin Constant');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (205,'Beruri');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (206,'Boa Vista do Ramos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (207,'Boca do Acre');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (208,'Borba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (209,'Caapiranga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (210,'Cametá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (211,'Canumã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (212,'Canutama');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (213,'Carauari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (214,'Careiro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (215,'Careiro da Várzea');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (216,'Carvoeiro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (217,'Coari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (218,'Codajás');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (219,'Cucuí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (220,'Eirunepé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (221,'Envira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (222,'Floriano Peixoto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (223,'Fonte Boa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (224,'Freguesia do Andirá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (225,'Guajará');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (226,'Humaitá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (227,'Iauaretê');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (228,'Içanã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (229,'Ipixuna');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (230,'Iranduba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (231,'Itacoatiara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (232,'Itamarati');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (233,'Itapiranga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (234,'Japurá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (235,'Juruá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (236,'Jutaí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (237,'Lábrea');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (238,'Lago Preto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (239,'Manacapuru');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (240,'Manaquiri');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (241,'Manaus');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (242,'Manicoré');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (243,'Maraã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (244,'Massauari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (245,'Maués');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (246,'Mocambo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (247,'Moura');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (248,'Murutinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (249,'Nhamundá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (250,'Nova Olinda do Norte');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (251,'Novo Airão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (252,'Novo Aripuanã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (253,'Osório da Fonseca');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (254,'Parintins');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (255,'Pauini');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (256,'Pedras');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (257,'Presidente Figueiredo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (258,'Repartimento');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (259,'Rio Preto da Eva');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (260,'Santa Isabel do Rio Negro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (261,'Santa Rita');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (262,'Santo Antônio do Içá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (263,'São Felipe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (264,'São Gabriel da Cachoeira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (265,'São Paulo de Olivença');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (266,'São Sebastião do Uatumã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (267,'Silves');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (268,'Tabatinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (269,'Tapauá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (270,'Tefé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (271,'Tonantins');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (272,'Uarini');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (273,'Urucará');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (274,'Urucurituba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (275,'Vila Pitinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (276,'Abacate da Pedreira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (277,'Serra do Navio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (278,'Amapá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (279,'Amapari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (280,'Ambé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (281,'Aporema');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (282,'Ariri');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (283,'Bailique');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (284,'Boca do Jari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (285,'Calçoene');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (286,'Cantanzal');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (287,'Carmo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (288,'Clevelândia do Norte');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (289,'Corre água');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (290,'Cunani');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (291,'Curiaú');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (292,'Cutias');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (293,'Fazendinha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (294,'Ferreira Gomes');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (295,'Fortaleza');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (296,'Gaivota');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (297,'Gurupora');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (298,'Igarapé do Lago');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (299,'Ilha de Santana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (300,'Inajá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (301,'Itaubal');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (302,'Laranjal do Jari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (303,'Livramento do Pacuí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (304,'Lourenço');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (305,'Macapá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (306,'Mazagão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (307,'Mazagão Velho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (308,'Oiapoque');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (309,'Paredão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (310,'Porto Grande');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (311,'Pracuúba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (312,'Santa Luzia do Pacuí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (313,'Santa Maria');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (314,'Santana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (315,'São Joaquim do Pacuí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (316,'São Sebastião do Livramento');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (317,'São Tomé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (318,'Serra do Navio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (319,'Sucuriju');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (320,'Tartarugalzinho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (321,'Vila Velha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (322,'Vitória do Jari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (323,'Abadia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (324,'Abaíra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (325,'Abaré');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (326,'Abelhas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (327,'Abóbora');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (328,'Abrantes');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (329,'Acajutiba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (330,'Açu da Torre');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (331,'Açudina');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (332,'Acupe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (333,'Adustina');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (334,'Afligidos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (335,'Afrânio Peixoto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (336,'Água Doce');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (337,'Água Fria');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (338,'Águas do Paulista');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (339,'Aiquara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (340,'Alagoinhas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (341,'Alcobaça');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (342,'Alegre');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (343,'Algodão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (344,'Algodões');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (345,'Almadina');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (346,'Alto Bonito');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (347,'Amado Bahia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (348,'Amaniú');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (349,'Amargosa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (350,'Amélia Rodrigues');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (351,'América Dourada');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (352,'Américo Alves');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (353,'Anagé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (354,'Andaraí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (355,'Andorinha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (356,'Angical');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (357,'Angico');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (358,'Anguera');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (359,'Antas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (360,'Antônio Cardoso');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (361,'Antônio Gonçalves');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (362,'Aporá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (363,'Apuarema');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (364,'Araçás');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (365,'Aracatu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (366,'Araci');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (367,'Aramari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (368,'Arapiranga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (369,'Arataca');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (370,'Aratuípe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (371,'Areias');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (372,'Arembepe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (373,'Argoim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (374,'Argolo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (375,'Aribice');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (376,'Aritaguá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (377,'Aurelino Leal');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (378,'Baianópolis');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (379,'Baixa do Palmeira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (380,'Baixa Grande');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (381,'Baixão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (382,'Baixinha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (383,'Baluarte');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (384,'Banco Central');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (385,'Banco da Vitória');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (386,'Bandeira do Almada');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (387,'Bandeira do Colônia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (388,'Bandiaçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (389,'Banzaê');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (390,'Baraúnas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (391,'Barcelos do Sul');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (392,'Barra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (393,'Barra da Estiva');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (394,'Barra do Choça');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (395,'Barra do Jacuípe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (396,'Barra do Mendes');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (397,'Barra do Pojuca');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (398,'Barra do Rocha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (399,'Barra do Tarrachil');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (400,'Barracas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (401,'Barreiras');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (402,'Barro Alto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (403,'Governador Lomanto Júnior');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (404,'Barro Vermelho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (405,'Barrocas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (406,'Bastião');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (407,'Bate Pé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (408,'Batinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (409,'Bela Flor');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (410,'Belém da Cachoeira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (411,'Belmonte');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (412,'Belo Campo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (413,'Belo Campo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (414,'Bem-bom');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (415,'Bendegó');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (416,'Bento Simões');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (417,'Biritinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (418,'Boa Espera');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (419,'Boa Nova');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (420,'Boa União');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (421,'Boa Vista do Lagamar');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (422,'Boa Vista do Tupim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (423,'Boaçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (424,'Boca do Córrego');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (425,'Bom Jesus da Lapa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (426,'Bom Jesus da Serra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (427,'Bom Sossego');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (428,'Bonfim da Feira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (429,'Boninal');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (430,'Bonito');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (431,'Boquira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (432,'Botuporã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (433,'Botuquara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (434,'Brejinho das Ametistas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (435,'Brejo da Serra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (436,'Brejo Luíza de Brito');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (437,'Brejo Novo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (438,'Brejões');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (439,'Brejolândia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (440,'Brotas de Macaúbas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (441,'Brumado');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (442,'Bucuituba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (443,'Buerarema');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (444,'Buracica');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (445,'Buranhém');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (446,'Buril');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (447,'Buris de Abrantes');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (448,'Buritirama');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (449,'Caatiba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (450,'Cabaceiras do Paraguaçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (451,'Cabrália');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (452,'Cacha Pregos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (453,'Cachoeira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (454,'Cachoeira do Mato');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (455,'Caculé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (456,'Caém');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (457,'Caetanos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (458,'Caeté-açu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (459,'Caetité');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (460,'Cafarnaum');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (461,'Caiçara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (462,'Caimbé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (463,'Cairu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (464,'Caiubi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (465,'Cajuí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (466,'Caldas do Jorro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (467,'Caldeirão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (468,'Caldeirão Grande');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (469,'Caldeiras');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (470,'Camacan');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (471,'Camaçari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (472,'Camamu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (473,'Camassandi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (474,'Camirim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (475,'Campinhos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (476,'Campo Alegre de Lourdes');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (477,'Campo Formoso');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (478,'Campo Formoso');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (479,'Camurugi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (480,'Canabravinha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (481,'Canápolis');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (482,'Canarana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (483,'Canatiba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (484,'Canavieiras');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (485,'Canché');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (486,'Candeal');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (487,'Candeias');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (488,'Candiba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (489,'Cândido Sales');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (490,'Canoão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (491,'Cansanção');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (492,'Canto do Sol');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (493,'Canudos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (494,'Canudos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (495,'Capão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (496,'Capela do Alto Alegre');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (497,'Capim Grosso');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (498,'Caraguataí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (499,'Caraíbas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (500,'Caraibuna');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (501,'Caraípe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (502,'Caraiva');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (503,'Caravelas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (504,'Cardeal da Silva');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (505,'Carinhanha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (506,'Caripare');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (507,'Carnaíba do Sertão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (508,'Carrapichel');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (509,'Casa Nova');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (510,'Castelo Novo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (511,'Castro Alves');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (512,'Catinga do Moura');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (513,'Catingal');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (514,'Catolândia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (515,'Catolés');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (516,'Catolezinho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (517,'Catu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (518,'Catu de Abrantes');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (519,'Caturama');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (520,'Cavunge');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (521,'Central');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (522,'Ceraima');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (523,'Chorrochó');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (524,'Cícero Dantas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (525,'Cinco Rios');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (526,'Cipó');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (527,'Coaraci');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (528,'Cocos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (529,'Colônia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (530,'Comércio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (531,'Conceição da Feira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (532,'Conceição do Almeida');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (533,'Conceição do Coité');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (534,'Conceição do Jacuípe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (535,'Conde');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (536,'Condeúba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (537,'Contendas do Sincorá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (538,'Copixaba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (539,'Coqueiros');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (540,'Coquinhos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (541,'Coração de Maria');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (542,'Cordeiros');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (543,'Coribe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (544,'Coronel João Sá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (545,'Correntina');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (546,'Corta Mão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (547,'Cotegipe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (548,'Coutos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (549,'Cravolândia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (550,'Crisópolis');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (551,'Cristalândia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (552,'Cristópolis');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (553,'Crussaí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (554,'Cruz das Almas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (555,'Cumuruxatiba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (556,'Cunhangi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (557,'Curaçá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (558,'Curral Falso');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (559,'Dário Meira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (560,'Delfino');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (561,'Descoberto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (562,'Dias Coelho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (563,'Dias D\'Ávila');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (564,'Diógenes Sampaio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (565,'Dom Basílio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (566,'Dom Macedo Costa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (567,'Dona Maria');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (568,'Duas Barras do Morro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (569,'Elísio Medrado');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (570,'Encruzilhada');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (571,'Engenheiro França');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (572,'Engenheiro Pontes');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (573,'Entre Rios');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (574,'Érico Cardoso');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (575,'Esplanada');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (576,'Euclides da Cunha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (577,'Eunápolis');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (578,'Fátima');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (579,'Feira da Mata');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (580,'Feira de Santana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (581,'Ferradas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (582,'Filadélfia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (583,'Filanésia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (584,'Firmino Alves');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (585,'Floresta Azul');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (586,'Formosa do Rio Preto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (587,'França');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (588,'Gabiarra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (589,'Galeão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (590,'Gamboa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (591,'Gameleira da Lapa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (592,'Gameleira do Assuruá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (593,'Gandu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (594,'Gavião');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (595,'Gentio do Ouro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (596,'Geolândia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (597,'Glória');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (598,'Gongogi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (599,'Governador João Durval Carneiro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (600,'Governador Mangabeira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (601,'Guagirus');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (602,'Guaí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (603,'Guajeru');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (604,'Guanambi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (605,'Guapira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (606,'Guarajuba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (607,'Guaratinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (608,'Guerém');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (609,'Guiné');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (610,'Guirapa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (611,'Gurupá Mirim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (612,'Heliópolis');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (613,'Helvecia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (614,'Hidrolândia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (615,'Humildes');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (616,'Iaçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (617,'Ibatui');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (618,'Ibiaçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (619,'Ibiajara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (620,'Ibiapora');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (621,'Ibiassucê');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (622,'Ibicaraí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (623,'Ibicoara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (624,'Ibicuí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (625,'Ibipeba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (626,'Ibipetum');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (627,'Ibipitanga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (628,'Ibiquera');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (629,'Ibiraba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (630,'Ibirajá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (631,'Ibiranhém');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (632,'Ibirapitanga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (633,'Ibirapuã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (634,'Ibirataia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (635,'Ibitiara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (636,'Ibitiguira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (637,'Ibitira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (638,'Ibititá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (639,'Ibitunane');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (640,'Ibitupa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (641,'Ibó');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (642,'Ibotirama');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (643,'Ichu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (644,'Icó');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (645,'Igaporã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (646,'Igará');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (647,'Igarité');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (648,'Igatu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (649,'Igrapiúna');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (650,'Iguá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (651,'Iguaí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (652,'Iguaibi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (653,'Iguatemi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (654,'Iguira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (655,'Iguitu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (656,'Ilha de Maré');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (657,'Ilhéus');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (658,'Indaí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (659,'Inema');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (660,'Inhambupe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (661,'Inhata');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (662,'Inhaúmas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (663,'Inhobim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (664,'Inúbia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (665,'Ipecaetá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (666,'Ipiaú');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (667,'Ipirá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (668,'Ipiúna');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (669,'Ipucaba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (670,'Ipupiara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (671,'Irajuba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (672,'Iramaia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (673,'Iraporanga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (674,'Iraquara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (675,'Irará');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (676,'Irecê');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (677,'Irundiara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (678,'Ita-azul');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (679,'Itabela');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (680,'Itaberaba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (681,'Itabuna');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (682,'Itacaré');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (683,'Itacava');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (684,'Itachama');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (685,'Itacimirim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (686,'Itaeté');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (687,'Itagi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (688,'Itagibá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (689,'Itagimirim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (690,'Itaguaçu da Bahia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (691,'Itaia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (692,'Itaibó');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (693,'Itaipu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (694,'Itaítu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (695,'Itajaí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (696,'Itaju do Colônia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (697,'Itajubaquara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (698,'Itajuípe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (699,'Itajuru');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (700,'Itamaraju');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (701,'Itamari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (702,'Itambé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (703,'Itamira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (704,'Itamotinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (705,'Itanagé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (706,'Itanagra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (707,'Itanhém');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (708,'Itanhi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (709,'Itaparica');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (710,'Itapé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (711,'Itapebi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (712,'Itapeipu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (713,'Itapetinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (714,'Itapicuru');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (715,'Itapirema');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (716,'Itapitanga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (717,'Itapora');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (718,'Itapura');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (719,'Itaquara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (720,'Itaquaraí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (721,'Itarantim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (722,'Itati');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (723,'Itatim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (724,'Itatingui');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (725,'Itiruçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (726,'Itiúba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (727,'Itororó');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (728,'Ituaçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (729,'Ituberá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (730,'Itupeva');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (731,'Iuiu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (732,'Jaborandi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (733,'Jacaraci');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (734,'Jacobina');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (735,'Jacu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (736,'Jacuípe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (737,'Jacuruna');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (738,'Jaguaquara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (739,'Jaguara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (740,'Jaguarari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (741,'Jaguaripe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (742,'Jaíba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (743,'Jandaíra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (744,'Japomirim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (745,'Japu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (746,'Jauá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (747,'Jequié');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (748,'Jequiriçá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (749,'Jeremoabo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (750,'Jiribatuba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (751,'Jitaúna');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (752,'João Amaro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (753,'João Correia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (754,'João Dourado');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (755,'José Gonçalves');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (756,'Juacema');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (757,'Juazeiro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (758,'Jucuruçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (759,'Juerana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (760,'Junco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (761,'Jupaguá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (762,'Juraci');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (763,'Juremal');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (764,'Jussara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (765,'Jussari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (766,'Jussiape');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (767,'Km Sete');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (768,'Lafaiete Coutinho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (769,'Lagoa Clara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (770,'Lagoa de Melquíades');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (771,'Lagoa do Boi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (772,'Lagoa Grande');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (773,'Lagoa Grande');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (774,'Lagoa José Luís');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (775,'Lagoa Preta');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (776,'Lagoa Real');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (777,'Laje');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (778,'Laje do Banco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (779,'Lajedão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (780,'Lajedinho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (781,'Lajedo Alto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (782,'Lajedo do Tabocal');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (783,'Lamarão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (784,'Lamarão do Passe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (785,'Lapão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (786,'Largo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (787,'Lauro de Freitas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (788,'Lençóis');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (789,'Licínio de Almeida');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (790,'Limoeiro do Bom Viver');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (791,'Livramento de Nossa Senhora');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (792,'Lucaia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (793,'Luís Viana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (794,'Lustosa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (795,'Macajuba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (796,'Macarani');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (797,'Macaúbas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (798,'Macururé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (799,'Madre de Deus');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (800,'Maetinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (801,'Maiquinique');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (802,'Mairi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (803,'Malhada');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (804,'Malhada de Pedras');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (805,'Mandiroba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (806,'Mangue Seco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (807,'Maniaçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (808,'Manoel Vitorino');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (809,'Mansidão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (810,'Mantiba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (811,'Mar Grande');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (812,'Maracás');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (813,'Maragogipe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (814,'Maragogipinho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (815,'Maraú');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (816,'Marcionílio Souza');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (817,'Marcolino Moura');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (818,'Maria Quitéria');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (819,'Maricoabo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (820,'Mariquita');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (821,'Mascote');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (822,'Massacara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (823,'Massaroca');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (824,'Mata da Aliança');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (825,'Mata de São João');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (826,'Mataripe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (827,'Matina');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (828,'Matinha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (829,'Medeiros Neto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (830,'Miguel Calmon');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (831,'Milagres');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (832,'Luís Eduardo Magalhães');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (833,'Minas do Espírito Santo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (834,'Minas do Mimoso');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (835,'Mirandela');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (836,'Miranga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (837,'Mirangaba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (838,'Mirante');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (839,'Mocambo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (840,'Mogiquiçaba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (841,'Monte Cruzeiro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (842,'Monte Gordo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (843,'Monte Recôncavo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (844,'Monte Santo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (845,'Morpará');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (846,'Morrinhos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (847,'Morro das Flores');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (848,'Morro de São Paulo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (849,'Morro do Chapéu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (850,'Mortugaba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (851,'Mucugê');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (852,'Mucuri');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (853,'Mulungu do Morro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (854,'Mundo Novo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (855,'Muniz Ferreira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (856,'Muquém de São Francisco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (857,'Muritiba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (858,'Mutas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (859,'Mutuípe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (860,'Nagé');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (861,'Narandiba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (862,'Nazaré');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (863,'Nilo Peçanha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (864,'Nordestina');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (865,'Nova Alegria');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (866,'Nova Brasília');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (867,'Nova Canaã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (868,'Nova Fátima');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (869,'Nova Ibiá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (870,'Nova Itaipê');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (871,'Nova Itarana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (872,'Nova Lídice');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (873,'Nova Redenção');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (874,'Nova Soure');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (875,'Nova Viçosa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (876,'Novo Acre');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (877,'Novo Horizonte');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (878,'Novo Triunfo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (879,'Núcleo Residencial Pilar');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (880,'Nuguaçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (881,'Olhos D\'Água do Seco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (882,'Olhos D\'Água do Serafim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (883,'Olindina');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (884,'Oliveira dos Brejinhos');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (885,'Olivença');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (886,'Onha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (887,'Oriente Novo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (888,'Ouricana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (889,'Ouriçangas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (890,'Ouricuri do Ouro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (891,'Ourolândia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (892,'Outeiro Redondo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (893,'Paiol');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (894,'Pajeú do Vento');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (895,'Palame');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (896,'Palmas de Monte Alto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (897,'Palmeiras');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (898,'Parafuso');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (899,'Paramirim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (900,'Parateca');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (901,'Paratinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (902,'Paripiranga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (903,'Pataíba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (904,'Patamuté');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (905,'Pau a Pique');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (906,'Pau Brasil');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (907,'Paulo Afonso');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (908,'Pé de Serra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (909,'Pedrão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (910,'Pedras Altas do Mirim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (911,'Pedro Alexandre');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (912,'Peixe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (913,'Petim');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (914,'Piabanha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (915,'Piatã');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (916,'Piçarrão');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (917,'Pilão Arcado');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (918,'Pimenteira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (919,'Pindaí');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (920,'Pindobaçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (921,'Pinhões');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (922,'Pintadas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (923,'Piragi');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (924,'Piraí do Norte');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (925,'Pirajá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (926,'Pirajuia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (927,'Piri');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (928,'Piripá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (929,'Piritiba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (930,'Pituba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (931,'Planaltino');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (932,'Planalto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (933,'Poço Central');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (934,'Poço de Fora');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (935,'Poções');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (936,'Poços');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (937,'Pojuca');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (938,'Polo Petroquímico de Camaçari');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (939,'Ponta da Areia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (940,'Ponto Novo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (941,'Porto Novo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (942,'Porto Seguro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (943,'Posto da Mata');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (944,'Potiraguá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (945,'Poxim do Sul');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (946,'Prado');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (947,'Presidente Dutra');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (948,'Presidente Jânio Quadros');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (949,'Presidente Tancredo Neves');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (950,'Prevenido');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (951,'Quaraçu');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (952,'Queimadas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (953,'Quijingue');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (954,'Quixabá');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (955,'Quixabeira');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (956,'Rafael Jambeiro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (957,'Recife');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (958,'Remanso');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (959,'Remédios');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (960,'Retirolândia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (961,'Riachão das Neves');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (962,'Riachão do Jacuípe');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (963,'Riachão do Utinga');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (964,'Riacho da Guia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (965,'Riacho de Santana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (966,'Riacho Seco');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (967,'Ribeira do Amparo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (968,'Ribeira do Pombal');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (969,'Ribeirão do Largo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (970,'Ribeirão do Salto');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (971,'Rio da Dona');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (972,'Rio de Contas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (973,'Rio do Antônio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (974,'Rio do Braço');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (975,'Rio do Meio');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (976,'Rio do Pires');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (977,'Rio Fundo');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (978,'Rio Real');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (979,'Rodelas');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (980,'Ruy Barbosa');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (981,'Saldanha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (982,'Salgadália');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (983,'Salinas da Margarida');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (984,'Salobrinho');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (985,'Salobro');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (986,'Salvador');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (987,'Sambaíba');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (988,'Santa Bárbara');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (989,'Santa Brígida');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (990,'Santa Cruz Cabrália');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (991,'Santa Cruz da Vitória');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (992,'Santa Inês');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (993,'Santa Luzia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (994,'Santa Maria da Vitória');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (995,'Santa Rita de Cássia');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (996,'Santa Terezinha');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (997,'Santaluz');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (998,'Santana');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (999,'Santana do Sobrado');
INSERT INTO `` (`id`,`nm_cidade`) VALUES (1000,'Santanópolis');
